[package]
name = "box"
version = "0.2.0"
description = "Manage shared 'box' directories. This utility allows for secure file giveaways inside the box."
authors = ["Christian Kauhaus <kc@flyingcircus.io>"]
license = "ZPL-2.1"
edition = "2018"

[dependencies]
clap = "2.30"
libc = "0.2"
users = "0.9"
walkdir = "2.2"
failure = "0.1.5"

[dev-dependencies]
tempdir = "0.3"
